version: "3.9"
services:
  frontend-dev:
    image: node:18-alpine
    working_dir: /app
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    command: sh -c "npm install && npm run dev"
    environment:
      - VITE_API_URL=http://localhost:8000
    env_file:
      - .env.dev

  frontend-prod:
    build: .
    image: btecai/frontend:latest
    ports:
      - "3000:80"
    environment:
      - VITE_API_URL=http://backend:8000
    env_file:
      - .env.prod