
services:
  frontend-dev:
    image: node:18-alpine
    container_name: btecai_frontend_dev
    working_dir: /app
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    command: sh -c "npm install && npm run dev -- --host"
    env_file:
      - .env
    # Không cần environment: VITE_API_URL, .env sẽ tự động được copy từ .env.dev hoặc .env.prod

  frontend-prod:
    build: .
    image: btecai/frontend:latest
    container_name: btecai_frontend_prod
    ports:
      - "3000:80"
    env_file:
      - .env