services:
  discord_bot_dev:
    build: .
    container_name: discord_bot_dev
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - .:/app
    command: python bot.py

  n8n:
    image: n8nio/n8n
    container_name: n8n
    restart: always
    ports:
      - "5678:5678"
    env_file:
      - .env
    volumes:
      - n8n_data:/home/node/.n8n
  nginx:
    image: nginx:alpine
    container_name: nginx_n8n_proxy
    restart: always
    ports:
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/nginx/certs:ro
    depends_on:
      - n8n

volumes:
  n8n_data: