services:
  discord_bot_dev:
    build: .
    container_name: discord_bot_dev
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - .:/app
    command: python run_watchgod.py # Chạy bot.py qua run_watchgod.py để tự động reload khi có thay đổi

  n8n:
    image: n8nio/n8n
    container_name: n8n
    restart: always
    env_file:
      - .env
    volumes:
      - n8n_data:/home/node/.n8n

volumes:
  n8n_data: