version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: fastapi_mysql_db
    restart: always
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  api:
    build: .
    container_name: fastapi_app
    restart: always
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app

volumes:
  db_data: