services:
  api:
    command: ["gunicorn", "-k", "uvicorn.workers.UvicornWorker", "--bind", "0.0.0.0:8000", "app.main:app"]
    environment:
      - ENV=prod
    volumes: []  # Không mount code, chỉ dùng image đã build