version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: fastapi_mysql_db
    restart: always
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  redis:
    image: redis:7.0-alpine
    container_name: fastapi_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --save 60 1 --loglevel warning
  
  api:
    build: .
    container_name: fastapi_app
    restart: always
    depends_on:
      - db
      - redis
    env_file:
      - .env
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PYTHONPATH=/app
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app

volumes:
  db_data:
  redis_data: